In [1]:
import preprocessing as pp
import pandas as pd
import numpy as np

# pickle to tuple 
mosi_train = pd.read_pickle('data/MOSI/train.pkl')
mosi_dev = pd.read_pickle('data/MOSI/dev.pkl')
mosi_test = pd.read_pickle('data/MOSI/dev.pkl')

mosei_train = pd.read_pickle('data/MOSEI/train.pkl')
mosei_dev = pd.read_pickle('data/MOSEI/dev.pkl')
mosei_test = pd.read_pickle('data/MOSEI/dev.pkl')

# ms_train = pp.tu2li(mosi_train)
# ms_dev = pp.tu2li(mosi_dev)
# ms_test = pp.tu2li(mosi_test)

# mse_train = pp.tu2li(mosei_train)
# mse_dev = pp.tu2li(mosei_dev)
# mse_test = pp.tu2li(mosei_test)

In [2]:
print(len(mosi_train))
# print(len(ms_dev))
# print(len(ms_test))
# print(len(mse_train))
# print(len(mse_dev))
# print(len(mse_test))

1283


In [3]:
print(mosi_train[0])

((array([2, 3, 4, 5, 6]), array([[-1.8661549 , -1.2940491 ,  0.81038904,  0.81038904,  1.7222605 ,
        -0.8811255 , -1.2511225 ,  0.80115855, -1.6071116 , -0.98933095,
         0.02300847,  0.91536343, -1.133718  ,  0.58758605, -0.19861473,
        -1.4494152 ,  1.784517  , -0.8688507 , -0.92644167,  0.79868764,
        -1.197538  , -0.9170206 ,  0.05840183,  1.0142266 , -0.8420491 ,
         0.6696255 , -0.6431462 , -0.68073314, -1.6797264 , -1.7025481 ,
         1.1693664 , -1.9658769 ,  1.4377642 ,  0.34900138, -1.5015361 ,
         1.4391537 , -1.934377  ,  0.490528  , -1.1778185 , -1.0122594 ,
        -1.5597491 ,  0.910458  , -0.51679957, -0.05288289, -1.048641  ,
         1.5732425 ,  1.8533574 ],
       [ 0.83710134, -0.17096134, -1.0971203 , -1.0971203 ,  0.35844085,
         0.97653234,  0.56652075, -0.9057386 , -0.51624024,  0.9578278 ,
         1.6783967 , -0.89941096,  1.1814458 , -1.6539545 ,  1.2267547 ,
         0.5352902 ,  0.2828254 ,  0.9492336 ,  0.2672226 , -1.

In [17]:
ms_txt = pp.modality_div(mosi_train, 0)
ms_aud = pp.modality_div(mosi_train, 2)
labels = pp.modality_div(mosi_train, -1)

ms_txt[0] = np.concatenate((np.array([212]), ms_txt[0]), axis = 0)
ms_txt[0]

array([212,   2,   3,   4,   5,   6])

In [63]:
len(ms_train[0])

3

In [64]:
ms_train[0][0]

(array([2, 3, 4, 5, 6]),
 array([[-1.8661549 , -1.2940491 ,  0.81038904,  0.81038904,  1.7222605 ,
         -0.8811255 , -1.2511225 ,  0.80115855, -1.6071116 , -0.98933095,
          0.02300847,  0.91536343, -1.133718  ,  0.58758605, -0.19861473,
         -1.4494152 ,  1.784517  , -0.8688507 , -0.92644167,  0.79868764,
         -1.197538  , -0.9170206 ,  0.05840183,  1.0142266 , -0.8420491 ,
          0.6696255 , -0.6431462 , -0.68073314, -1.6797264 , -1.7025481 ,
          1.1693664 , -1.9658769 ,  1.4377642 ,  0.34900138, -1.5015361 ,
          1.4391537 , -1.934377  ,  0.490528  , -1.1778185 , -1.0122594 ,
         -1.5597491 ,  0.910458  , -0.51679957, -0.05288289, -1.048641  ,
          1.5732425 ,  1.8533574 ],
        [ 0.83710134, -0.17096134, -1.0971203 , -1.0971203 ,  0.35844085,
          0.97653234,  0.56652075, -0.9057386 , -0.51624024,  0.9578278 ,
          1.6783967 , -0.89941096,  1.1814458 , -1.6539545 ,  1.2267547 ,
          0.5352902 ,  0.2828254 ,  0.9492336 ,  0.

In [65]:
len(ms_train[0][0])

4

In [66]:
ms_train[0][1]

array([[2.4]], dtype=float32)

In [86]:
type(mosi_train[0][1][0][0])

numpy.float32

In [67]:
len(ms_train[0][1])

1

In [68]:
ms_train[0][2]

'03bSnISJMiM[0]'

In [69]:
len(ms_train[0][2])

14

In [83]:
print(mosi_train[0][0][0])

[2 3 4 5 6]


In [84]:
print(type(mosi_train[0][0][0]))

<class 'numpy.ndarray'>


In [74]:
print(ms_train[0][0][2])

[[-1.2934351  -0.4437256  -0.23228365 -0.20061648 -0.10547926 -1.5979109
  -0.34951994  0.7648991   0.04449983  1.69712     0.5261609   0.25567028
   0.07920387 -0.98555064 -1.5019004  -0.97605145  0.5372735   1.1903144
   0.6253898  -0.70413786  0.7904706  -0.60345596  0.31274977 -0.76777875
  -0.7211172   0.95856136  0.63161236 -0.6304974   1.1020092   0.47864896
  -0.96303946  0.20850182  0.27882013  0.17925519  0.02109092  0.06375107
   0.          0.          0.          0.          0.          0.
   0.          0.8232074  -0.08291677  0.15465455  1.5851582   1.8975486
   0.9021025   0.9787147   0.9892046   1.2918522   1.0054917   1.2790707
  -0.50571173  0.5861894   0.7082402   1.6516232  -0.2883293   0.09596142
  -1.924665   -0.4879121  -0.13714421  0.8780444   1.3932003   1.5175604
  -0.1725963  -1.1102616  -1.1856349  -0.84383863 -0.22944187 -0.3885516
  -0.57278734 -0.23394847]
 [ 1.6133617  -1.1309779  -1.4015676  -1.7954227   0.60422164 -0.37006313
   0.959874   -0.6358803 

In [75]:
print(ms_train[0][0][3])

['anyhow', 'it', 'was', 'really', 'good']


In [15]:
len(ms_train[0][0][3])

5

In [16]:
ms_train[0][1]

array([[2.4]], dtype=float32)

In [17]:
len(ms_train[0][1])

1

In [18]:
ms_train[0][2]

'03bSnISJMiM[0]'

In [19]:
len(ms_train[0][2])

14

In [21]:
ms_train1 = pp.del2idx(ms_train)
ms_dev1 = pp.del2idx(ms_dev)
ms_test1 = pp.del2idx(ms_test)

In [37]:
type(ms_train1[0][1][0][0])

numpy.float32

In [38]:
import torch
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

text = 'I love programming with PyTorch'
input_ids = tokenizer.encode(text, add_special_tokens = True)

print(input_ids)

ImportError: cannot import name 'TypeAlias' from 'typing_extensions' (/home/jaegookyu/.conda/envs/jaegookyu/lib/python3.8/site-packages/typing_extensions.py)